### ISSUE TITLE
Request: clarification on scoping and private modules 

### ISSUE THREAD

**Issue by kevinSuttle** [npm/npmo-docs#6]
In terms of npmo, there is quite a bit of confusion in terms of what is "private" and when scope is needed. 

Questions I get
- [x] Does scoping make modules private automatically? 
- [x] Does publishing to an npmo registry _require_ scoping?
- [x] Does publishing to an npmo registry make modules private to both the public registry _and_ the npmo registry?

**Comment by nexdrew** [comment]
@kevinSuttle These are good questions. Here's my best shot at answers:

> Does scoping make modules private automatically?

According to the default behavior of the `npm` CLI client, yes it does, because in order to publish a scoped package to the public registry you have to run `npm publish --access public`, and you have to have access to the scope in the public registry. This is one of the main reasons we encourage everyone publishing private packages to a private npm Enterprise registry to use a scope for package names.

Is it possible to accidentally publish a scoped package to the public registry? Yes, but it is _much_ harder to do so by accident than it is for unscoped packages.

> Does publishing to an npmo registry require scoping?

Technically no. There are a couple ways you can configure your `npm` client (or even an individual package) to point to your private registry without using a scope, but for reasons mentioned above (among others) we highly recommend using a scope for _all_ private packages.

> Does publishing to an npmo registry make modules private to both the public registry and the npmo registry?

No. Packages published to npm Enterprise are not published to an upstream registry, particularly not the public registry. One of the main reasons to use npm Enterprise is that you maintain complete control over the packages that you publish - they belong to you and they live _only_ on your server(s). Access to packages published to npm Enterprise is defined by your configured authn/authz provider which is controlled by you or your organization. The access control used by the public registry is different and completely separate.

**Comment by kevinSuttle** [comment]
Thanks so much for the thorough answers @nexdrew. These should be put into the npme docs under FAQ and linked to from the scope docs. 

For me, it makes sense to _require_ scopes when logging in and publishing. Like, 'throw an error' require.

**Comment by kevinSuttle** [comment]
Or maybe that's part of https://github.com/npm/enterprise-configurator/issues/41 and it's set via npm config, and the user is constantly reminded anytime any command is run which scope and registry she is pointing at.

**Comment by nexdrew** [comment]
@kevinSuttle [npm/enterprise-configurator](https://github.com/npm/enterprise-configurator) is probably not the best place to herd these requests together. `enterprise-configurator` is a tool we have used to handle common requirements among npm's internal microservice components, and we're even starting to move away from using it since it's a little quirky and we have better ways of providing its functionality.

That being said, we are currently working on another tool where we should be able to start implementing some of your requests. Unfortunately it's not ready for primetime yet and has not been open-sourced at this time (so I can't point you to it), but please know your requests are not falling on deaf ears.

At this time, the best place to aggregate npmE-specific requests is probably https://github.com/npm/npme-installer/issues.

**Comment by kevinSuttle** [comment]
Right on. I'm already working with @bcoe. He hears all about it. :)
